# Creates an entry in html/changelogs_ch automatically, to eventually be compiled by compile_changelogs
name: Auto Changelog
on:
  pull_request_target:
    types: closed
    branches:
      - master

env:
  BASENAME: "chompstation"

jobs:
  autochangelog:
    name: Autochangelog
    runs-on: ubuntu-20.04
    permissions:
      contents: write # to push to branch
      pull-requests: write # to create pull requests (repo-sync/pull-request)
    concurrency: 
      group: autochangelog_group
      cancel-in-progress: false
    if: github.event.pull_request.merged == true && ( contains(github.event.pull_request.body, ':cl:') || contains(github.event.pull_request.body, '🆑') )
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run auto changelog
      uses: actions/github-script@v6
      with:
        script: |
          const { processAutoChangelog } = await import('${{ github.workspace }}/tools/pull_request_hooks/autoChangelog.js')
          await processAutoChangelog({ github, context })
        github-token: ${{ secrets.COMFY_ORANGE_PAT || secrets.GITHUB_TOKEN }}
